AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cab-app

  Checkmate accountability bot SAM

Parameters:
  AwsRegion:
    Type: String
    Description: Aws service region
    Default: local
  SlackBotToken:
    Type: String
    Description: Slack bot token
    Default: token

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Environment:
      Variables:
        AwsRegion: !Ref AwsRegion
        SlackBotToken: !Ref SlackBotToken

Resources:
  EventGatewayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/event/gateway
      Handler: event-gateway
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events
            Method: POST
  EventTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/event/task
      Handler: event-task
      Runtime: go1.x
      Architectures:
        - x86_64
  InteractionGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/interaction/gateway
      Handler: interaction-gateway
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /interactions
            Method: POST
  InteractionTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/interaction/task
      Handler: interaction-task
      Runtime: go1.x
      Architectures:
        - x86_64
  ShufflerFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: lambda/shuffler
      Handler: shuffler
      Runtime: go1.x
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: "cron(0 6 ? * 1 *)"
            Name: AccountabilityShuffleSchedule
            Description: cron to run the shuffler function weekly
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: checkmateafrica-users
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  PairsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: checkmateafrica-pairs
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
